- name: Setup vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Setup Variable
      include_vars: /home/ubuntu/Projects/vpcstack/bastion_setup.yml

    - name: Import VPC Setup Variable
      include_vars: /home/ubuntu/Projects/variables/output_vars

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile_key
        region: "{{region}}" 
      register: key_out

    - name: Saving Private Key file in bastion pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create SG for Bastion Host
      ec2_group:
        name: Bastion_host-SG
        description: Allow port22 from everywhere and all port within SG  
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Creating Bastion Host
      ec2:
        key_name: vprofile_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: vprofile
          Owner: DevOps Team
        exact_count: 1
        count_tag: 
          Name: "Bastion_host"
          Project: vprofile
          Owner: DevOps Team
        group_id:  "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out



